### PR TITLE
Update _About.js

### PR DESCRIPTION
**Pull request by s-s5678**
Changes in Footer to Dynamically update the current year

### CODE REVIEW

**Review by seema6789 — COMMENTED** [review]
Footer updated well!

**Review by seema6789 — APPROVED** [review]
Update approved

**Review by seema6789 — CHANGES_REQUESTED** [review]
Okay

**Comment by seema6789** [comment]
reviewed

**Comment by praveenscience** [comment]
@s-s5678 @seema6789 This looks good, is there an issue for this? 🤔

**Comment by praveenscience** [comment]
No response, closing it.

**Pull request closed without merging**
