### PR TITLE
Removed all changes

### LINKED ISSUE #30: Remove Parent Testimonials Justify
I would like to work on this issue. Please assign this to me.

### PR DESCRIPTION
**Pull request by akshatvirmani**
fixes #30

### CODE REVIEW

**Comment by praveenscience** [comment]
Please link the PR.

**Review by praveenscience — CHANGES_REQUESTED** [review]
Please link the PR.
Remove the `package-lock.json`.

**Review by praveenscience — CHANGES_REQUESTED** [review]
Can you please remove the `package-lock.json` changes. Not the file from this PR. This shouldn't affect the file `package-lock.json`.

**Comment by praveenscience** [comment]
Can we please have this closed by today, please?

**Comment by akshatvirmani** [comment]
Yes Sir

**Comment by praveenscience** [comment]
Just close this PR and create a new PR man.

**Pull request closed without merging**
