### PR TITLE
Added Scroll Top feature in each page of website

### PR DESCRIPTION
**Pull request by SharmaTanish**
Hi @praveenscience !
I have successfully added Scroll to top feature in each and every page present on website. On clicking on the button in right bottom corner above chat button having above arrow icon, smooth scrolling of web page takes place till it reaches the top done by using `window.scrollBy` method.
Please have a look on this and merge it.
Thank You

### CODE REVIEW

**Comment by SharmaTanish** [comment]
This pull request is solving issue #14 !

**Comment by praveenscience** [comment]
I need to look through this in detail man and then will merge it... 🔥 It's using some DOM stuff, etc...

**Comment by SharmaTanish** [comment]
@praveenscience sir have you reviewed?
Please give me feedback?

**Comment by praveenscience** [comment]
@SharmaTanish Not yet man, I'll do it by the end of day today, okay? 😊

**Comment by SharmaTanish** [comment]
Hi @praveenscience , please review and merge it asap , because you know tomorrow is last date of GSSOC !
Thank you

**Comment by SharmaTanish** [comment]
@praveenscience I request you to please review and merge it as today is last date of GSSOC!!!!!
I have just made a scroll top component in Home page component folder and just rendered it in each component/page we have in our project. It is not a very big task to review!
Thank you
Regards

**Comment by SharmaTanish** [comment]
Thank you @praveenscience sir for your support!

**Pull request merged**
